# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - template: shared/validate-stage.yml

  - stage: build_and_publish
    displayName: "Build and Publish"
    jobs:
      - job: build_and_publish_package
        displayName: "Build and Publish Package"
        steps:
          - template: shared/npm-steps.yml
          - task: Npm@1
            inputs:
              command: "custom"
              customCommand: "run compile"
            displayName: "Build Package"

          - task: Npm@1
            inputs:
              command: "custom"
              customCommand: "publish"
            displayName: "Publish Package"
